chore: add a pre-commit hook to prevent accidentally using internal NPM Registry :\

diff --git a/lefthook.yml b/lefthook.yml
--- a/lefthook.yml
+++ b/lefthook.yml
@@ -19,3 +19,13 @@ pre-push:
     actionlint:
       root: .github/workflows/
       run: actionlint
+pre-commit:
+  commands:
+    internal-artifactory:
+      run: |
+        if fgrep -q square-npm pnpm-lock.yaml; then
+          echo "error: pnpm-lock.yaml contains square-npm references"
+          exit 1
+        else
+          exit 0
+        fi
